blacklist: []
build_space: odroid-build
catkin_make_args: []
cmake_args:
- -DCMAKE_TOOLCHAIN_FILE=/home/zargol/catkin_ws_user/src/Toolchain-arm-linux-gnueabihf.cmake
devel_space: odroid-devel
extend_path: /opt/odroid-x2/sdk/opt/ros/indigo/
install: true
install_space: odroid-install
isolate_devel: false
isolate_install: false
make_args: []
source_space: src
use_internal_make_jobserver: true
whitelist: []
